### ISSUE TITLE
statistics not applying to the folder I add them to

### ISSUE THREAD

**Issue by Sjokie46** [Justtolook/RemNote-Statistics-Plugin#3]
When I want to few the statistics for a folder and use /statistics on that folder.
The statistics are filled with info about all my rems over my whole remote period, instead of just that folder.

A feature suggest:
- past 30-days few
- all-time few (folder specific ofc.)

**Comment by Sjokie46** [comment]
Is there any new about these new features?

**Comment by Justtolook** [comment]
Function implemented with bd1e96f2376362b616bcbe7692849eed5f4a6558
